//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeMaze.MazeSolverService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MazeSolverService.MazeSolverServiceSoap")]
    public interface MazeSolverServiceSoap {
        
        // CODEGEN: Generating message contract since element name maze from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazeSolver", ReplyAction="*")]
        CodeMaze.MazeSolverService.MazeSolverResponse MazeSolver(CodeMaze.MazeSolverService.MazeSolverRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MazeSolver", ReplyAction="*")]
        System.Threading.Tasks.Task<CodeMaze.MazeSolverService.MazeSolverResponse> MazeSolverAsync(CodeMaze.MazeSolverService.MazeSolverRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MazeSolverRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MazeSolver", Namespace="http://tempuri.org/", Order=0)]
        public CodeMaze.MazeSolverService.MazeSolverRequestBody Body;
        
        public MazeSolverRequest() {
        }
        
        public MazeSolverRequest(CodeMaze.MazeSolverService.MazeSolverRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MazeSolverRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string maze;
        
        public MazeSolverRequestBody() {
        }
        
        public MazeSolverRequestBody(string maze) {
            this.maze = maze;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MazeSolverResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MazeSolverResponse", Namespace="http://tempuri.org/", Order=0)]
        public CodeMaze.MazeSolverService.MazeSolverResponseBody Body;
        
        public MazeSolverResponse() {
        }
        
        public MazeSolverResponse(CodeMaze.MazeSolverService.MazeSolverResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MazeSolverResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MazeSolverResult;
        
        public MazeSolverResponseBody() {
        }
        
        public MazeSolverResponseBody(string MazeSolverResult) {
            this.MazeSolverResult = MazeSolverResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MazeSolverServiceSoapChannel : CodeMaze.MazeSolverService.MazeSolverServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MazeSolverServiceSoapClient : System.ServiceModel.ClientBase<CodeMaze.MazeSolverService.MazeSolverServiceSoap>, CodeMaze.MazeSolverService.MazeSolverServiceSoap {
        
        public MazeSolverServiceSoapClient() {
        }
        
        public MazeSolverServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MazeSolverServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MazeSolverServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MazeSolverServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CodeMaze.MazeSolverService.MazeSolverResponse CodeMaze.MazeSolverService.MazeSolverServiceSoap.MazeSolver(CodeMaze.MazeSolverService.MazeSolverRequest request) {
            return base.Channel.MazeSolver(request);
        }
        
        public string MazeSolver(string maze) {
            CodeMaze.MazeSolverService.MazeSolverRequest inValue = new CodeMaze.MazeSolverService.MazeSolverRequest();
            inValue.Body = new CodeMaze.MazeSolverService.MazeSolverRequestBody();
            inValue.Body.maze = maze;
            CodeMaze.MazeSolverService.MazeSolverResponse retVal = ((CodeMaze.MazeSolverService.MazeSolverServiceSoap)(this)).MazeSolver(inValue);
            return retVal.Body.MazeSolverResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CodeMaze.MazeSolverService.MazeSolverResponse> CodeMaze.MazeSolverService.MazeSolverServiceSoap.MazeSolverAsync(CodeMaze.MazeSolverService.MazeSolverRequest request) {
            return base.Channel.MazeSolverAsync(request);
        }
        
        public System.Threading.Tasks.Task<CodeMaze.MazeSolverService.MazeSolverResponse> MazeSolverAsync(string maze) {
            CodeMaze.MazeSolverService.MazeSolverRequest inValue = new CodeMaze.MazeSolverService.MazeSolverRequest();
            inValue.Body = new CodeMaze.MazeSolverService.MazeSolverRequestBody();
            inValue.Body.maze = maze;
            return ((CodeMaze.MazeSolverService.MazeSolverServiceSoap)(this)).MazeSolverAsync(inValue);
        }
    }
}
